version: '3.9'

services:
#  app:
#    container_name: fastapi
#    build:
#      context: ./src
#      dockerfile: Dockerfile
#    command: bash -c "poetry run alembic upgrade heads && poetry run uvicorn main:app --host 0.0.0.0 --port 8000"
#    ports:
#      - '8000:8000'
#    env_file: .env
#    depends_on:
#      - db
#      - cache
  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  cache:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5
    restart: unless-stopped
